### ISSUE TITLE
Build crashes when stripEmptyTranslations is set to true

### ISSUE THREAD

**Issue by mdcarreira** [ember-intl/ember-intl#1661]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.20.7
- Ember CLI Version: 3.20.2
- Ember Intl Version: 5.7.2
- Browser(s): ---
- Node Version: 12.22.0

### Steps to Reproduce

I'm trying to activate `stripEmptyTranslations`, but when I do the build crashes with this error:

```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Proxying to http://127.0.0.1:9000
Build Error (TranslationReducer)

Cannot convert undefined or null to object

Stack Trace and Error Report: /tmp/error.dump.edd63f55bc196b24a7aa3939c0b9f1fe.log
```

Looking into the referred log file, we have this:
```
=================================================================================

ENV Summary:

  TIME: Tue Apr 26 2022 09:51:25 GMT+0100 (Western European Summer Time)
  TITLE: ember
  ARGV:
  - /home/micael/.volta/tools/image/node/12.22.0/bin/node
  - /home/micael/code/weldnote-frontend/node_modules/.bin/ember
  - s
  EXEC_PATH: /home/micael/.volta/tools/image/node/12.22.0/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /home/micael/.volta/tools/image/npm/7.24.1/bin
  - /home/micael/.volta/tools/image/yarn/1.22.10/bin
  - /home/micael/.volta/tools/image/node/12.22.0/bin
  - /home/micael/.volta/bin
  - /home/micael/.sdkman/candidates/sbt/current/bin
  - /home/micael/.sdkman/candidates/java/current/bin
  - /home/micael/.volta/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  PLATFORM: linux x64
  FREEMEM: 9730908160
  TOTALMEM: 33408757760
  UPTIME: 3387
  LOADAVG: 2.32,2.19,1.85
  CPUS:
  - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz - 3547
  - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz - 3525
  - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz - 3565
  - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz - 3539
  - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz - 3576
  - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz - 3528
  - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz - 3514
  - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz - 3573
  - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz - 3561
  - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz - 3510
  - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz - 3558
  - Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz - 3578
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.16.1
  - brotli: 1.0.9
  - cldr: 37.0
  - http_parser: 2.9.4
  - icu: 67.1
  - llhttp: 2.1.3
  - modules: 72
  - napi: 8
  - nghttp2: 1.41.0
  - node: 12.22.0
  - openssl: 1.1.1j
  - tz: 2019c
  - unicode: 13.0
  - uv: 1.40.0
  - v8: 7.8.279.23-node.46
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at stripEmptyTranslations (/home/micael/code/weldnote-frontend/node_modules/ember-intl/lib/broccoli/translation-reducer/utils/strip-empty-translations.js:14:10)
    at /home/micael/code/weldnote-frontend/node_modules/ember-intl/lib/broccoli/translation-reducer/index.js:132:23
    at Array.reduce (<anonymous>)
    at TranslationReducer.mergeTranslations (/home/micael/code/weldnote-frontend/node_modules/ember-intl/lib/broccoli/translation-reducer/index.js:123:32)
    at TranslationReducer.build (/home/micael/code/weldnote-frontend/node_modules/ember-intl/lib/broccoli/translation-reducer/index.js:219:31)
    at /home/micael/code/weldnote-frontend/node_modules/broccoli-caching-writer/index.js:149:21
    at tryCatch (/home/micael/code/weldnote-frontend/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/micael/code/weldnote-frontend/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/micael/code/weldnote-frontend/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/home/micael/code/weldnote-frontend/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:2415:5)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
  - code: [undefined]
  - codeFrame: Cannot convert undefined or null to object
  - errorMessage: Cannot convert undefined or null to object
        at TranslationReducer (Translation Reducer)
-~- created here: -~-
    at TranslationReducer.Plugin (/home/micael/code/weldnote-frontend/node_modules/broccoli-plugin/index.js:7:31)
    at new CachingWriter (/home/micael/code/weldnote-frontend/node_modules/broccoli-caching-writer/index.js:18:10)
    at new TranslationReducer (/home/micael/code/weldnote-frontend/node_modules/ember-intl/lib/broccoli/translation-reducer/index.js:62:5)
    at Class.generateTranslationTree (/home/micael/code/weldnote-frontend/node_modules/ember-intl/index.js:71:12)
    at Class.treeForAddon (/home/micael/code/weldnote-frontend/node_modules/ember-intl/index.js:97:36)
    at Class.superWrapper [as treeForAddon] (/home/micael/code/weldnote-frontend/node_modules/core-object/lib/assign-properties.js:34:20)
    at Class._treeFor (/home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/models/addon.js:668:33)
    at Class.treeFor (/home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/models/addon.js:628:21)
    at /home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:701:26
    at Array.reduce (<anonymous>)
    at EmberApp._addonTreesFor (/home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:699:32)
    at EmberApp._addonBundles (/home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1112:31)
    at EmberApp.createAddonTree (/home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1125:29)
    at EmberApp.addonTree (/home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1143:36)
    at EmberApp.getExternalTree (/home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1191:25)
    at EmberApp.toArray (/home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1543:12)
-~- (end) -~-
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: Cannot convert undefined or null to object
        at TranslationReducer (Translation Reducer)
-~- created here: -~-
    at TranslationReducer.Plugin (/home/micael/code/weldnote-frontend/node_modules/broccoli-plugin/index.js:7:31)
    at new CachingWriter (/home/micael/code/weldnote-frontend/node_modules/broccoli-caching-writer/index.js:18:10)
    at new TranslationReducer (/home/micael/code/weldnote-frontend/node_modules/ember-intl/lib/broccoli/translation-reducer/index.js:62:5)
    at Class.generateTranslationTree (/home/micael/code/weldnote-frontend/node_modules/ember-intl/index.js:71:12)
    at Class.treeForAddon (/home/micael/code/weldnote-frontend/node_modules/ember-intl/index.js:97:36)
    at Class.superWrapper [as treeForAddon] (/home/micael/code/weldnote-frontend/node_modules/core-object/lib/assign-properties.js:34:20)
    at Class._treeFor (/home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/models/addon.js:668:33)
    at Class.treeFor (/home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/models/addon.js:628:21)
    at /home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:701:26
    at Array.reduce (<anonymous>)
    at EmberApp._addonTreesFor (/home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:699:32)
    at EmberApp._addonBundles (/home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1112:31)
    at EmberApp.createAddonTree (/home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1125:29)
    at EmberApp.addonTree (/home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1143:36)
    at EmberApp.getExternalTree (/home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1191:25)
    at EmberApp.toArray (/home/micael/code/weldnote-frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1543:12)
-~- (end) -~-
  - name: Error
  - nodeAnnotation: Translation Reducer
  - nodeName: TranslationReducer
  - originalErrorMessage: Cannot convert undefined or null to object
  - stack: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at stripEmptyTranslations (/home/micael/code/weldnote-frontend/node_modules/ember-intl/lib/broccoli/translation-reducer/utils/strip-empty-translations.js:14:10)
    at /home/micael/code/weldnote-frontend/node_modules/ember-intl/lib/broccoli/translation-reducer/index.js:132:23
    at Array.reduce (<anonymous>)
    at TranslationReducer.mergeTranslations (/home/micael/code/weldnote-frontend/node_modules/ember-intl/lib/broccoli/translation-reducer/index.js:123:32)
    at TranslationReducer.build (/home/micael/code/weldnote-frontend/node_modules/ember-intl/lib/broccoli/translation-reducer/index.js:219:31)
    at /home/micael/code/weldnote-frontend/node_modules/broccoli-caching-writer/index.js:149:21
    at tryCatch (/home/micael/code/weldnote-frontend/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/home/micael/code/weldnote-frontend/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/home/micael/code/weldnote-frontend/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/home/micael/code/weldnote-frontend/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:2415:5)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

=================================================================================
```

I checked the arguments being passed to `stripEmptyTranslations` function, and all args (object, objectKey, objectParent) were `undefined`, causing the build to crash.

Anybody has any idea why this might be happening? Do you think the `stripEmptyTranslations` function should perform a null check or the problem should be solved at another level?

**Comment by ijlee2** [comment]
Closing this issue, as there isn't a reproduction repo and I don't have capacity to support `ember-intl@v5` and `node@v12`. It's possible that, with `ember-intl@v6` (for which the packages `@formatjs/*` have been updated)` and/or higher versions of `ember-source`, the issue may not occur.
