### ISSUE TITLE
Tests fail with Ember v2.12

### ISSUE THREAD

**Issue by anehx** [ember-intl/ember-intl#604]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 2.12.2
- Ember CLI Version: 3.3.0
- Ember Intl Version: 3.2.1
- Browser(s): Chrome 68
- Node Version: 6.14.4

### Steps to Reproduce

* Check out https://github.com/projectcaluma/ember-caluma-form-builder on branch `renovate/ember-intl-3.x`
* Run `ember try:one ember-lts-2.12`

### Description

My renovatebot tried to upgrade `ember-intl` in an [addon](https://github.com/projectcaluma/ember-caluma-form-builder/pull/53) from `v3.1.1` to `v3.2.1` but my tests for ember `v2.12.2` failed. This was the error message for all of the tests:

```
TypeError: Cannot read property 'pushObject' of undefined
                at Class.localeFactory (http://localhost:7357/assets/vendor.js:207442:20)
                at Class.translationsFor (http://localhost:7357/assets/vendor.js:208616:28)
                at Class.addTranslations (http://localhost:7357/assets/vendor.js:208608:25)
                at http://localhost:7357/assets/vendor.js:208210:15
                at Array.forEach (<anonymous>)
                at exports.default (http://localhost:7357/assets/vendor.js:208207:18)
                at Class.init (http://localhost:7357/assets/vendor.js:208530:28)
                at Class.superWrapper [as init] (http://localhost:7357/assets/vendor.js:52265:22)
                at new Class (http://localhost:7357/assets/vendor.js:47976:19)
                at Function._ClassMixinProps.create (http://localhost:7357/assets/vendor.js:48168:12)
```

**Comment by jasonmit** [comment]
Resolved in 3.2.4.  Thanks for reporting!
