### ISSUE TITLE
broccoli-persistent-filter: t(...).isPlaceholder is not a function

### ISSUE THREAD

**Issue by ultimatemonty** [ember-intl/ember-intl#850]
- [x] I am on the [latest](https://github.com/ember-intl/ember-intl/releases/latest) ember-intl version
- [x] I have searched the [issues](https://github.com/ember-intl/ember-intl/issues) of this repo and believe that this is not a duplicate

### Environment

- Ember Version: 3.4.6
- Ember CLI Version: 3.9.0
- Ember Intl Version: 3.5.2
- Browser(s): n/a (fails to build)
- Node Version: 10.13.0

### Steps to Reproduce
Not sure exactly how to repro but here's some additional details from my app. Please let know if you need any additional info and I'll be happy to add it!

```
➜  ember version --verbose
ember-cli: 3.9.0
http_parser: 2.8.0
node: 10.13.0
v8: 6.8.275.32-node.36
uv: 1.23.2
zlib: 1.2.11
ares: 1.14.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0i
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
os: darwin x64
```

**package.json**
```
"dependencies": {
	"@ember-decorators/babel-transforms": "^2.0.0",
	"d3": "^5.0.0",
	"d3-selection-multi": "^1.0.1",
	"ember-cli-babel": "^6.16.0",
	"ember-cli-htmlbars": "^3.0.0",
	"ember-cli-htmlbars-inline-precompile": "^1.0.3",
	"ember-cli-sass": "^8.0.1",
	"ember-d3": "^0.4.4",
	"ember-decorators": "^2.5.2",
	"ember-intl": "^3.5.0",
	"ember-steps": "^6.1.2",
	"moment": "^2.22.1"
},
"devDependencies": {
	"@ember-decorators/babel-transforms": "^2.0.0",
	"@ember/jquery": "^0.5.2",
	"@ember/optional-features": "^0.6.3",
	"babel-eslint": "^8.0.0",
	"broccoli-asset-rev": "^2.7.0",
	"ember-ajax": "^3.1.0",
	"ember-angle-bracket-invocation-polyfill": "^1.2.3",
	"ember-cli": "^3.4.4",
	"ember-cli-app-version": "^3.2.0",
	"ember-cli-babel": "^6.16.0",
	"ember-cli-code-coverage": "1.0.0-beta.5",
	"ember-cli-dependency-checker": "^3.0.0",
	"ember-cli-dependency-lint": "^1.1.3",
	"ember-cli-eslint": "^4.2.3",
	"ember-cli-htmlbars": "^3.0.0",
	"ember-cli-htmlbars-inline-precompile": "^1.0.3",
	"ember-cli-inject-live-reload": "^1.8.2",
	"ember-cli-mirage": "^0.4.10",
	"ember-cli-moment-shim": "^3.7.1",
	"ember-cli-qunit": "^4.3.2",
	"ember-cli-shims": "^1.2.0",
	"ember-cli-sri": "^2.1.1",
	"ember-cli-template-lint": "^1.0.0-beta.1",
	"ember-cli-uglify": "^2.1.0",
	"ember-concurrency": "^0.8.17",
	"ember-concurrency-decorators": "^0.1.0",
	"ember-d3": "^0.4.4",
	"ember-decorators": "^2.5.2",
	"ember-disable-prototype-extensions": "^1.1.2",
	"ember-export-application-global": "^2.0.0",
	"ember-intl": "^3.5.0",
	"ember-load-initializers": "^1.0.0",
	"ember-lodash": "^4.18.0",
	"ember-maybe-import-regenerator": "^0.1.6",
	"ember-resolver": "^5.0.1",
	"ember-sinon": "^2.1.0",
	"ember-sinon-qunit": "^3.1.0",
	"ember-source": "~3.4.0",
	"ember-source-channel-url": "^1.1.0",
	"ember-try": "^0.2.23",
	"ember-uuid": "^1.0.1",
	"eslint": "^5.7.0",
	"eslint-plugin-ember": "^5.2.0",
	"eslint-plugin-node": "^6.0.1",
	"loader.js": "^4.7.0",
	"prettier": "^1.14.3",
	"qunit-dom": "^0.7.1",
	"sass": "^1.14.1"
},
"resolutions": {
	"eslint-scope": "3.7.1"
},
"engines": {
	"node": "6.* || 8.* || >= 10.*"
}
```

**full error log**
```
 - broccoliBuilderErrorStack: TypeError: t(...).isPlaceholder is not a function
    at placeholderVisitorHandler (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/template/lib/parse.js:81:11)
    at traverseSimpleImpl (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/types/lib/traverse/traverse.js:27:14)
    at Object.traverse (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/types/lib/traverse/traverse.js:21:3)
    at parseAndBuildMetadata (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/template/lib/parse.js:65:7)
    at buildLiteralData (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/template/lib/literal.js:53:35)
    at literalTemplate (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/template/lib/literal.js:20:7)
    at Function.ast (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/template/lib/builder.js:52:42)
    at Object.ast (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/helpers/lib/helpers.js:26:42)
    at fn (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/helpers/lib/index.js:245:30)
    at loadHelper (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/helpers/lib/index.js:248:40)
  - code: [undefined]
  - codeFrame: t(...).isPlaceholder is not a function
  - errorMessage: ember-intl/test-support/add-translations.js: t(...).isPlaceholder is not a function
        in /var/folders/7t/f0ch8jsn03jg4snyz6q6tfzcz9r1k1/T/broccoli-91437oA3LwWeQztG6/out-026-analyzer_ember_auto_import_analyzer
        at broccoli-persistent-filter:Babel > [Babel: ember-intl] (Babel: ember-intl)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: ember-intl/test-support/add-translations.js
    - line: [undefined]
    - treeDir: /var/folders/7t/f0ch8jsn03jg4snyz6q6tfzcz9r1k1/T/broccoli-91437oA3LwWeQztG6/out-026-analyzer_ember_auto_import_analyzer
  - message: ember-intl/test-support/add-translations.js: t(...).isPlaceholder is not a function
        in /var/folders/7t/f0ch8jsn03jg4snyz6q6tfzcz9r1k1/T/broccoli-91437oA3LwWeQztG6/out-026-analyzer_ember_auto_import_analyzer
        at broccoli-persistent-filter:Babel > [Babel: ember-intl] (Babel: ember-intl)
  - name: BuildError
  - nodeAnnotation: Babel: ember-intl
  - nodeName: broccoli-persistent-filter:Babel > [Babel: ember-intl]
  - originalErrorMessage: t(...).isPlaceholder is not a function
  - stack: TypeError: t(...).isPlaceholder is not a function
    at placeholderVisitorHandler (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/template/lib/parse.js:81:11)
    at traverseSimpleImpl (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/types/lib/traverse/traverse.js:27:14)
    at Object.traverse (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/types/lib/traverse/traverse.js:21:3)
    at parseAndBuildMetadata (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/template/lib/parse.js:65:7)
    at buildLiteralData (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/template/lib/literal.js:53:35)
    at literalTemplate (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/template/lib/literal.js:20:7)
    at Function.ast (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/template/lib/builder.js:52:42)
    at Object.ast (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/helpers/lib/helpers.js:26:42)
    at fn (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/helpers/lib/index.js:245:30)
    at loadHelper (/Users/cmcculler/Projects/Pardot/fulcrum/node_modules/ember-intl/node_modules/@babel/helpers/lib/index.js:248:40)
```

**Comment by jasonmit** [comment]
Unsure but you have ember-intl as a dep and a devDep, that's not necessary.

I believe this issue is an artifact of a bug in a dependency.  I'll keep this open for visibility.

**Comment by jasonmit** [comment]
Is this still an issue and if so can anyone help reproduce it for me?

**Comment by ultimatemonty** [comment]
@jasonmit I'll try this out again in the next few days and get back to you. Sorry for letting it languish

**Comment by jasonmit** [comment]
Closing because issue seems to have gone stale.
